[package]
name = "rust-sqlx-prac"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = {version = "0.8.2", features = ["runtime-tokio", "uuid", "chrono", "macros", "postgres", "migrate"]}
tokio = {version = "1.42.0", features = ["macros", "rt-multi-thread"]}
